### ISSUE TITLE
ip_forward на ISP

### ISSUE THREAD

**Issue by d0mitoridesu** [storm39mad/DEMO2022#1]
После редактирования 
```bash
nano /etc/sysctl.conf
```
```ini
net.ipv4.ip_forward=1
```
нужно применить изменения
```bash
sysctl -p
```
или перезагрузить VM

**Comment by storm39mad** [comment]
![image](https://user-images.githubusercontent.com/79700810/150780594-fbd25aed-11be-441f-ae19-cfa27bcb9b10.png)
